name: Build and publish
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  make_bin:
    name: Build binary
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Pre-build
        run: sudo apt install -y libfuse-dev pkg-config
      - uses: actions/checkout@v2
      - name: Build binary
        run: cargo build --release
      - name: Upload binary
        uses: actions/upload-artifact@v1
        with:
          name: mus-fuse
          path: ./target/release/mus-fuse
  make_arch:
      name: Make Arch Linux package
      runs-on: ubuntu-latest
      container:
        image: archlinux
        options: --privileged
        volumes:
          - /sys/fs/cgroup:/sys/fs/cgroup
      steps:
        - uses: actions/checkout@v2
        - name: Build Arch Linux package
          uses: house-of-vanity/build-arch-package@master
          with:
            PKGBUILD: $GITHUB_WORKSPACE/.github/workflows/PKGBUILD
            OUTDIR: $HOME/arch-packages
        - run: mv $HOME/arch-packages/*pkg.tar.zst mus-fuse-x86_64.pkg.tar.zst
        - name: Upload Arch Package
          uses: actions/upload-artifact@v1
          with:
            name: arch_linux_mus-fuse-x86_64.pkg.tar.zst
            path: ./mus-fuse-x86_64.pkg.tar.zst
  make_deb:
    name: Make Deb package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Pre-build
        run: sudo apt install -y libfuse-dev pkg-config && cargo install cargo-deb
      - uses: actions/checkout@v2
      - name: Build deb
        run: cargo deb --output ./target/debian/mus-fuse_amd64.deb
      - name: Upload binary
        uses: actions/upload-artifact@v1
        with:
          name: mus-fuse_amd64.deb
          path: ./target/debian/mus-fuse_amd64.deb

  publish:
    name: Publish release
    needs: [make_bin, make_deb, make_arch]
    runs-on: ubuntu-latest
    steps:
      - name: Get the version (git tag)
        id: get_version
        run: |
          echo ${GITHUB_REF/refs\/tags\/v/}
          echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\/v/}
          echo ::set-output name=FULL_TAG::${GITHUB_REF/refs\/tags\//}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Download binary
        uses: actions/download-artifact@v1
        with:
          name: mus-fuse
          path: ./artifacts/
      - name: Download Arch Package
        uses: actions/download-artifact@v1
        with:
          name: arch_linux_mus-fuse-x86_64.pkg.tar.zst
          path: ./artifacts/
      - name: Download Deb Package
        uses: actions/download-artifact@v1
        with:
          name: mus-fuse_amd64.deb
          path: ./artifacts/
      - name: Upload binary assets
        run: |
           apt install tree
           tree ./
           ls -lh ./artifacts
           wget https://github.com/aktau/github-release/releases/download/v0.7.2/linux-amd64-github-release.tar.bz2
           tar xjf linux-amd64-github-release.tar.bz2
           export GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
           ./bin/linux/amd64/github-release upload -u house-of-vanity -r mus-fuse --tag ${{ steps.get_version.outputs.FULL_TAG }} --name mus-fuse_${{ steps.get_version.outputs.VERSION }}_amd64.deb --file ./artifacts/mus-fuse_amd64.deb
           ./bin/linux/amd64/github-release upload -u house-of-vanity -r mus-fuse --tag ${{ steps.get_version.outputs.FULL_TAG }} --name arch_linux_mus-fuse-${{ steps.get_version.outputs.VERSION }}-x86_64.pkg.tar.zst --file ./artifacts/arch_linux_mus-fuse-x86_64.pkg.tar.zst
           ./bin/linux/amd64/github-release upload -u house-of-vanity -r mus-fuse --tag ${{ steps.get_version.outputs.FULL_TAG }} --name mus-fuse-${{ steps.get_version.outputs.VERSION }} --file ./artifacts/mus-fuse
#     - name: Upload Arch Linux Release
#       uses: actions/upload-release-asset@v1
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#       with:
#         upload_url: ${{ steps.create_release.outputs.upload_url }}
#         asset_path: ./mus-fuse/arch_linux_mus-fuse-x86_64.pkg.tar.zst
#         asset_name: arch_linux_mus-fuse-${{ steps.get_version.outputs.VERSION }}-x86_64.pkg.tar.zst
#         asset_content_type: application/zstd;
#     - name: Upload Deb Release
#       uses: actions/upload-release-asset@v1
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#       with:
#         upload_url: ${{ steps.create_release.outputs.upload_url }}
#         asset_path: ./mus-fuse/mus-fuse_${{ steps.get_version.outputs.VERSION }}_amd64.deb
#         asset_name: mus-fuse_amd64.deb
#         asset_content_type: application/vnd.debian.binary-package;
#     - name: Upload Binary Release
#       uses: actions/upload-release-asset@v1
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#       with:
#         upload_url: ${{ steps.create_release.outputs.upload_url }}
#         asset_path: ./mus-fuse/mus-fuse
#         asset_name: mus-fuse-${{ steps.get_version.outputs.VERSION }}
#         asset_content_type: application/x-pie-executable;
